INSERT INTO TB_POKEMON(name) VALUES('Bulbasaur');
INSERT INTO TB_POKEMON(name) VALUES('Charmander');
INSERT INTO TB_POKEMON(name) VALUES('Squirtle');
INSERT INTO TB_POKEMON(name) VALUES('Caterpie');
INSERT INTO TB_POKEMON(name) VALUES('Pikachu');


INSERT INTO TB_TYPE(description) VALUES('Poison');
INSERT INTO TB_TYPE(description) VALUES('Grass');
INSERT INTO TB_TYPE(description) VALUES('Fire');
INSERT INTO TB_TYPE(description) VALUES('Water');
INSERT INTO TB_TYPE(description) VALUES('Bug');
INSERT INTO TB_TYPE(description) VALUES('Flying');
INSERT INTO TB_TYPE(description) VALUES('Normal');
INSERT INTO TB_TYPE(description) VALUES('Eletric');
INSERT INTO TB_TYPE(description) VALUES('Ground');
INSERT INTO TB_TYPE(description) VALUES('Fairy');
INSERT INTO TB_TYPE(description) VALUES('Fighting');
INSERT INTO TB_TYPE(description) VALUES('Psychic');
INSERT INTO TB_TYPE(description) VALUES('Rock');
INSERT INTO TB_TYPE(description) VALUES('Steel');
INSERT INTO TB_TYPE(description) VALUES('Ghost');
INSERT INTO TB_TYPE(description) VALUES('Ice');
INSERT INTO TB_TYPE(description) VALUES('Dragon');


INSERT INTO REL_POKEMON_TYPE(TYPE_ID, POKEMON_ID) VALUES(2,1);
INSERT INTO REL_POKEMON_TYPE(TYPE_ID, POKEMON_ID) VALUES(1,1);
INSERT INTO REL_POKEMON_TYPE(TYPE_ID, POKEMON_ID) VALUES(3,2);
INSERT INTO REL_POKEMON_TYPE(TYPE_ID, POKEMON_ID) VALUES(4,3);
INSERT INTO REL_POKEMON_TYPE(TYPE_ID, POKEMON_ID) VALUES(5,4);
INSERT INTO REL_POKEMON_TYPE(TYPE_ID, POKEMON_ID) VALUES(8,5);
